# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-02 08:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('github', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Build',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('status', models.IntegerField(choices=[(10, 'Created'), (20, 'Running'), (100, 'Done'), (9999, 'Cancelled')], default=10)),
                ('result', models.IntegerField(choices=[(0, 'Pending'), (10, 'Fail'), (19, 'Qualified pass'), (20, 'Pass')], default=0)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Change',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('status', models.IntegerField(choices=[(10, 'New'), (100, 'Active'), (1000, 'Attic'), (9999, 'Ignored')], default=100)),
                ('change_type', models.IntegerField(choices=[(10, 'Pull Request'), (20, 'Push')])),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('completed', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(10, 'New'), (100, 'Active'), (1000, 'Attic'), (9999, 'Ignored')], default=10)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('repository', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='github.Repository')),
            ],
            options={
                'ordering': ('repository__name',),
            },
        ),
        migrations.AddField(
            model_name='change',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='projects.Project'),
        ),
        migrations.AddField(
            model_name='change',
            name='pull_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='github.PullRequest'),
        ),
        migrations.AddField(
            model_name='change',
            name='push',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='github.Push'),
        ),
        migrations.AddField(
            model_name='build',
            name='change',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='builds', to='projects.Change'),
        ),
        migrations.AddField(
            model_name='build',
            name='commit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='builds', to='github.Commit'),
        ),
    ]
