# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-08 02:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_tweak_model_ordering'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='error',
            field=models.TextField(blank=True),
        ),
    ]
