# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-26 05:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_add_commit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='build',
            name='commit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='builds', to='github.Commit'),
        ),
        migrations.AlterField(
            model_name='build',
            name='pull_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='builds', to='github.PullRequest'),
        ),
    ]
