# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-18 09:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_non_critical_tasks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(db_index=True, max_length=100)),
                ('key', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=2043)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variables', to='projects.Project')),
            ],
            options={
                'ordering': ('task_name', 'key'),
            },
        ),
    ]
