# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-18 09:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_add_variables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variable',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variables', to='projects.Project'),
        ),
    ]
