# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-18 10:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_add_global_variables'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variable',
            options={'ordering': ('descriptor', 'key')},
        ),
        migrations.RenameField(
            model_name='variable',
            old_name='task_name',
            new_name='descriptor',
        ),
        migrations.AlterUniqueTogether(
            name='variable',
            unique_together=set([('project', 'descriptor', 'key')]),
        ),
    ]
