# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-18 11:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_descriptor_not_task_name'),
    ]

    operations = [
        migrations.RenameModel('Variable', 'ProjectSetting'),
    ]
