# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-07 08:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_tweak_model_ordering'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(10, 'Created'), (19, 'Pending'), (20, 'Running'), (100, 'Done'), (200, 'Error'), (9998, 'Stopping'), (9999, 'Stopped')], default=10)),
                ('result', models.IntegerField(choices=[(0, 'Pending'), (10, 'Fail'), (19, 'Qualified pass'), (20, 'Pass')], default=0)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('slug', models.CharField(db_index=True, max_length=100)),
                ('phase', models.IntegerField()),
                ('started', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('completed', models.DateTimeField(blank=True, null=True)),
                ('descriptor', models.CharField(max_length=100)),
                ('arn', models.CharField(blank=True, max_length=100, null=True)),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.Build')),
            ],
            options={
                'ordering': ('phase', 'name'),
            },
        ),
        migrations.AlterUniqueTogether(
            name='task',
            unique_together=set([('build', 'slug')]),
        ),
    ]
