# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-15 04:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws', '0004_add_overrides'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='pending',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
