# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-15 05:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws', '0005_add_pending_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='error',
            field=models.TextField(blank=True),
        ),
    ]
