# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-20 04:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws', '0007_add_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.CharField(db_index=True, max_length=100)),
                ('instance_type', models.CharField(choices=[('t2.nano', 't2.nano'), ('t2.micro', 't2.micro'), ('t2.small', 't2.small'), ('t2.medium', 't2.medium'), ('t2.large', 't2.large'), ('t2.xlarge', 't2.xlarge'), ('t2.2xlarge', 't2.2xlarge'), ('m4.large', 'm4.large'), ('m4.xlarge', 'm4.xlarge'), ('m4.2xlarge', 'm4.2xlarge'), ('m4.4xlarge', 'm4.4xlarge'), ('m4.10xlarge', 'm4.10xlarge'), ('m4.16xlarge', 'm4.16xlarge'), ('c4.large', 'c4.large'), ('c4.xlarge', 'c4.xlarge'), ('c4.2xlarge', 'c4.2xlarge'), ('c4.4xlarge', 'c4.4xlarge'), ('c4.8xlarge', 'c4.8xlarge'), ('p2.xlarge', 'p2.xlarge'), ('p2.8xlarge', 'p2.8xlarge'), ('p2.16xlarge', 'p2.16xlarge'), ('g3.4xlarge', 'g3.4xlarge'), ('g3.8xlarge', 'g3.8xlarge'), ('g3.16xlarge', 'g3.16xlarge'), ('r4.large', 'r4.large'), ('r4.xlarge', 'r4.xlarge'), ('r4.2xlarge', 'r4.2xlarge'), ('r4.4xlarge', 'r4.4xlarge'), ('r4.8xlarge', 'r4.8xlarge'), ('r4.16xlarge', 'r4.16xlarge')], max_length=20)),
                ('cpu', models.IntegerField(default=0)),
                ('memory', models.IntegerField(default=0)),
                ('ami', models.CharField(default='ami-57d9cd2e', max_length=100)),
                ('idle', models.IntegerField(default=60)),
            ],
            options={
                'ordering': ('slug',),
            },
        ),
    ]
