# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-21 03:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('aws', '0008_add_task_profiles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_arn', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('ec2_id', models.CharField(db_index=True, max_length=100)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('checked', models.DateTimeField(auto_now=True)),
                ('terminated', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='idle',
            new_name='cooldown',
        ),
        migrations.AddField(
            model_name='profile',
            name='timeout',
            field=models.IntegerField(default=3600),
        ),
        migrations.AlterField(
            model_name='profile',
            name='ami',
            field=models.CharField(default='ami-57d9cd2e', max_length=100, verbose_name='AMI'),
        ),
        migrations.AddField(
            model_name='instance',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='aws.Profile'),
        ),
        migrations.AddField(
            model_name='instance',
            name='tasks',
            field=models.ManyToManyField(blank=True, to='aws.Task'),
        ),
    ]
