# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-21 03:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws', '0010_add_instance_limits'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='profile',
            new_name='profile_slug',
        ),
        migrations.AlterField(
            model_name='task',
            name='profile_slug',
            field=models.CharField(default='default', max_length=100),
        ),
    ]
