# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-21 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws', '0011_clarify_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='pending',
            new_name='queued',
        ),
        migrations.AlterField(
            model_name='instance',
            name='tasks',
            field=models.ManyToManyField(blank=True, related_name='instances', to='aws.Task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.IntegerField(choices=[(10, 'Created'), (19, 'Waiting'), (20, 'Running'), (100, 'Done'), (200, 'Error'), (9998, 'Stopping'), (9999, 'Stopped')], default=10),
        ),
    ]
