# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-07 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws', '0013_add_spot'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='preferred',
            field=models.BooleanField(default=False),
        ),
    ]
