# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-08-27 02:42
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws', '0014_preferred_instances'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='image',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='instance_type',
            field=models.CharField(choices=[('t2.nano', 't2.nano'), ('t2.micro', 't2.micro'), ('t2.small', 't2.small'), ('t2.medium', 't2.medium'), ('t2.large', 't2.large'), ('t2.xlarge', 't2.xlarge'), ('t2.2xlarge', 't2.2xlarge'), ('m4.large', 'm4.large'), ('m4.xlarge', 'm4.xlarge'), ('m4.2xlarge', 'm4.2xlarge'), ('m4.4xlarge', 'm4.4xlarge'), ('m4.10xlarge', 'm4.10xlarge'), ('m4.16xlarge', 'm4.16xlarge'), ('c5.large', 'c5.large'), ('c5.xlarge', 'c5.xlarge'), ('c5.2xlarge', 'c5.2xlarge'), ('c5.4xlarge', 'c5.4xlarge'), ('c5.9xlarge', 'c5.9xlarge'), ('c5.18xlarge', 'c5.18xlarge'), ('c4.large', 'c4.large'), ('c4.xlarge', 'c4.xlarge'), ('c4.2xlarge', 'c4.2xlarge'), ('c4.4xlarge', 'c4.4xlarge'), ('c4.8xlarge', 'c4.8xlarge'), ('p2.xlarge', 'p2.xlarge'), ('p2.8xlarge', 'p2.8xlarge'), ('p2.16xlarge', 'p2.16xlarge'), ('g3.4xlarge', 'g3.4xlarge'), ('g3.8xlarge', 'g3.8xlarge'), ('g3.16xlarge', 'g3.16xlarge'), ('r4.large', 'r4.large'), ('r4.xlarge', 'r4.xlarge'), ('r4.2xlarge', 'r4.2xlarge'), ('r4.4xlarge', 'r4.4xlarge'), ('r4.8xlarge', 'r4.8xlarge'), ('r4.16xlarge', 'r4.16xlarge')], max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='environment',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True),
        ),
    ]
