# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-02 08:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(db_index=True, max_length=100)),
                ('sha', models.CharField(db_index=True, max_length=40)),
                ('created', models.DateTimeField()),
                ('message', models.TextField()),
                ('url', models.URLField()),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='PullRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(db_index=True)),
                ('github_id', models.IntegerField(db_index=True)),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('html_url', models.URLField()),
                ('diff_url', models.URLField()),
                ('patch_url', models.URLField()),
                ('state', models.IntegerField(choices=[(10, 'Open'), (100, 'Closed')], default=10)),
            ],
            options={
                'ordering': ('number',),
            },
        ),
        migrations.CreateModel(
            name='PullRequestUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField()),
                ('commit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pull_request_updates', to='github.Commit')),
                ('pull_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='github.PullRequest')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='Push',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField()),
                ('commit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pushes', to='github.Commit')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('github_id', models.IntegerField(db_index=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('html_url', models.URLField()),
                ('description', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name_plural': 'repositories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_id', models.IntegerField(db_index=True)),
                ('login', models.CharField(db_index=True, max_length=100)),
                ('avatar_url', models.URLField()),
                ('html_url', models.URLField()),
                ('user_type', models.IntegerField(choices=[(10, 'User'), (20, 'Organization')], default=10)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='github_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('login',),
            },
        ),
        migrations.AddField(
            model_name='repository',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repositories', to='github.User'),
        ),
        migrations.AddField(
            model_name='pullrequest',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pull_requests', to='github.Repository'),
        ),
        migrations.AddField(
            model_name='pullrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pull_requests', to='github.User'),
        ),
        migrations.AddField(
            model_name='commit',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commits', to='github.Repository'),
        ),
        migrations.AddField(
            model_name='commit',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commits', to='github.User'),
        ),
    ]
