# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-08 01:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='push',
            options={'ordering': ('created',), 'verbose_name_plural': 'pushes'},
        ),
        migrations.AlterField(
            model_name='pullrequest',
            name='updated',
            field=models.DateTimeField(),
        ),
    ]
