# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-25 02:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='repository',
            options={'verbose_name_plural': 'repositories'},
        ),
        migrations.AddField(
            model_name='pullrequest',
            name='diff_url',
            field=models.URLField(default='http://example.com/diff'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pullrequest',
            name='patch_url',
            field=models.URLField(default='http://example.com/patch'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pullrequest',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='github_pull_requests', to='github.Repository'),
        ),
        migrations.AlterField(
            model_name='pullrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='github_pull_requests', to='github.User'),
        ),
        migrations.AlterField(
            model_name='repository',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='github_repositories', to='github.User'),
        ),
    ]
