# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-11 05:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0002_tweak_ordering'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'branches',
                'ordering': ('name',),
            },
        ),
        migrations.AlterModelOptions(
            name='pullrequest',
            options={'ordering': ('repository__name', 'number')},
        ),
        migrations.RenameField(
            model_name='commit',
            old_name='branch',
            new_name='branch_name',
        ),
        migrations.AddField(
            model_name='repository',
            name='master_branch_name',
            field=models.CharField(default='master', max_length=100),
        ),
        migrations.AddField(
            model_name='branch',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='github.Repository'),
        ),
    ]
