# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-25 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0003_rename_related_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='pullrequest',
            name='title',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
    ]
