# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-26 05:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0005_add_commit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pullrequest',
            old_name='merge_commit',
            new_name='commit',
        ),
    ]
