# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-26 05:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0006_rename_merge_commit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pullrequest',
            name='commit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pull_requests', to='github.Commit'),
        ),
    ]
